Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6], 
              [2, 8], 
              [3, 11],
              [3, 10],
              [1, 7]])

In [3]:
mean_a = a.mean(axis=0)

In [5]:
a_centered = a - mean_a

In [6]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [10]:
a_centered_1 = a_centered[:, :1]

In [11]:
a_centered_1

array([[-1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [-1.]])

In [12]:
a_centered_2 = a_centered[:, 1:]

In [13]:
a_centered_2

array([[-2.4],
       [-0.4],
       [ 2.6],
       [ 1.6],
       [-1.4]])

In [22]:
a_centered_sp = (a_centered_1 * a_centered_2).sum()

In [23]:
a_centered_sp

8.0

In [24]:
print(a_centered_sp / (a.shape[0] - 1))

2.0
